### ISSUE TITLE
delete bucket 

### ISSUE THREAD

**Issue by arch3rPro** [lzwme/scoop-proxy-cn#25]
please delete bucket：https://github.com/arch3rPro/scoop-bucket

**Comment by arch3rPro** [comment]
从这个项目中移除这个bucket！！！

**Comment by renxia** [comment]
您好，当前收集列表中并未直接包含该仓库，基于本仓库当前的同步机制无法进行详细列表的判定。您可能需要从直接依赖的仓库中申请移除，则基于当前仓库的同步机制也会自动移除。

可以从该列表中详细查看所有应用的直接来源： https://[raw.githubusercontent.com/lzwme/scoop-proxy-cn/main/sync-sources.txt](https://raw.githubusercontent.com/lzwme/scoop-proxy-cn/main/sync-sources.txt)

**Comment by arch3rPro** [comment]
请移除bucket [https://github.com/okibcn/ScoopMaster](https://github.com/okibcn/ScoopMaster)

**Comment by arch3rPro** [comment]
请停止侵权行为！
