### ISSUE TITLE
ghproxy.com 打不开了

### ISSUE THREAD

**Issue by freeok** [lzwme/scoop-proxy-cn#29]
ghproxy.net
gh-proxy.com 
正常

**Comment by renxia** [comment]
收到

**Comment by pcdd-group** [comment]
官网发通知了，喜提GFW

**Comment by renxia** [comment]
> 官网发通知了，喜提GFW

gh-proxy 速度上应该还可以的？

**Comment by yb6b** [comment]
https://gh-proxy.com/ 现在访问已经 502 Bad Gateway了。
可以用的网站：
- https://mirror.ghproxy.com/
- https://ghproxy.net/
- https://gh.api.99988866.xyz/

**Comment by yb6b** [comment]
或许可以fork一下scoop仓库，修改 current/lib/install.ps1 的源码，实现自动判断使用哪个镜像。

**Comment by zodiacg** [comment]
> 或许可以fork一下scoop仓库，修改 current/lib/install.ps1 的源码，实现自动判断使用哪个镜像。

国内有做 https://gitee.com/glsnames/scoop-installer。但配合spc不太行，spc bucket已经硬编码了ghproxy

**Comment by renxia** [comment]
请执行如下命令以重新添加：

```bash
# 更新 scoop repo
scoop config scoop_repo  https://mirror.ghproxy.com/github.com/ScoopInstaller/Scoop.git

# 移除并重新添加 spc bucket
scoop bucket rm spc
scoop bucket add spc https://mirror.ghproxy.com/github.com/lzwme/scoop-proxy-cn
```

**Comment by pcdd-group** [comment]
mirror.ghproxy.com 又双叒叕无了
