### ISSUE TITLE
Aida64-Bu Hash check failed!

### ISSUE THREAD

**Issue by fvydjt** [lzwme/scoop-proxy-cn#3]
ERROR Message:
Checking hash of aida64business685.zip ... ERROR Hash check failed!
App:         spc/Aida64-Bu
URL:         http://download.aida64.com/aida64business685.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    ac4275d2042f2d54a0ff9137095029a23717ef20dadffac3ef5d0b1065fde891
Actual:      5cca16379a78c132893c94d7726671bd17b021996ea89280a301665c815ce188

**Comment by renxia** [comment]
好像可以直接下载成功，重试一次试试？

**Comment by renxia** [comment]
您好，看了一下manifest内容，是没有对gist内容做处理，已修复。感谢您的反馈！

**Comment by fvydjt** [comment]
> 您好，看了一下manifest内容，是没有对gist内容做处理，已修复。感谢您的反馈！

还是有问题，即使在update之后还是相同的问题，最后我通过自己修改manifest的hash解决。
原hash：
"hash": [
        "ac4275d2042f2d54a0ff9137095029a23717ef20dadffac3ef5d0b1065fde891",
        "eb3cca82be1f3e581bee9377f183227ab0c2e0b723b85f6da7e38e9e986224e6"
    ],
修改后：
"hash": [
    "5cca16379a78c132893c94d7726671bd17b021996ea89280a301665c815ce188",
    "eb3cca82be1f3e581bee9377f183227ab0c2e0b723b85f6da7e38e9e986224e6"
  ],

**Comment by renxia** [comment]
这个是从第三方同步的，可能需要从其仓库中查找原因才行
考虑增加一个字段标记来源仓库用于追踪出处
