### ISSUE TITLE
无法安装main bucket 且无法安装spc bucket，导致无法使用

### ISSUE THREAD

**Issue by wgll000** [lzwme/scoop-proxy-cn#34]
PS C:\Users\Administrator> scoop bucket list
WARN  No bucket found. Please run 'scoop bucket add main' to add the default 'main' bucket.
PS C:\Users\Administrator> scoop bucket add main
ERROR Git is required for buckets. Run 'scoop install git' and try again.

**Comment by renxia** [comment]
安装一个git
https://git-scm.com/downloads

**Comment by wgll000** [comment]
请问是否能仿照https://github.com/duzyn/scoop-cn项目自动从镜像源安装git，有时下载git也会失败

**Comment by renxia** [comment]
安装git的操作应该该由用户自行决定。这里更新一下安装指引应该会好一些
