### ISSUE TITLE
scoop install todesk

### ISSUE THREAD

**Issue by ljchengx** [lzwme/scoop-proxy-cn#35]
https://mirror.ghproxy.com/github.com/lzwme/scoop-proxy-cn/issues/new?title=todesk%404.7.2.0%3a+hash+check+failed

**Comment by renxia** [comment]
由于部分 app 配置的下载地址为最新发布地址，但同时又配置了 hash 值，当其有新版本变更时则会出现 Hash Check Failed 的问题。此时可以添加参数 -s 以忽略

**Comment by ljchengx** [comment]
加了-s没问题了 感谢
