### ISSUE TITLE
notepad--的bucket好久没更新了~作者都更新了很多版本了

### ISSUE THREAD

**Issue by jcifox** [lzwme/scoop-proxy-cn#37]
https://github.com/cxasm/notepad--/releases

**Comment by renxia** [comment]
https://github.com/lzwme/scoop-proxy-cn/blob/559e542253bbefbc131bf91cd26c944444b4b29f/sync-sources.txt#L6089

通过来源记录，该应用 bucket 来源于该仓库：https://github.com/zhoujin7/tomato
已有相关反馈：https://github.com/zhoujin7/tomato/issues/17

可视情况提 PR 催促原作者解决
简单看了一下，应该只是因为 `autoupdate` 配置的 URL 路径大小写出现了变更
