### ISSUE TITLE
aliyundrive 403 forbidden 阿里云盘禁止访问

### ISSUE THREAD

**Issue by theSprog** [lzwme/scoop-proxy-cn#40]
❯ scoop install aliyundrive
Installing 'aliyundrive' (4.13.1) [64bit] from spc bucket
The remote server returned an error: (403) Forbidden.
URL https://cdn.aliyundrive.net/downloads/apps/desktop/update/4.13.1/win32/ia32/aDrive-4.13.1.exe#/aDrive-4.13.1.7z is not valid

~\Desktop
❯ scoop install aliyundrive
WARN  Purging previous failed installation of aliyundrive.
ERROR 'aliyundrive' isn't installed correctly.
Removing older version (4.13.1).
'aliyundrive' was uninstalled.
Installing 'aliyundrive' (4.13.1) [64bit] from spc bucket
The remote server returned an error: (403) Forbidden.
URL https://cdn.aliyundrive.net/downloads/apps/desktop/update/4.13.1/win32/ia32/aDrive-4.13.1.exe#/aDrive-4.13.1.7z is not valid

看起来似乎是阿里云盘不希望从 scoop 下载？
我用 chrome 访问下载链接是可以的

**Comment by renxia** [comment]
个人没有测试过。实际上几个大厂的应用，个人都不建议用scoop，直接下载后安装最好。
因为默认安装与scoop安装后的目录结构差异大，而这些大厂又都喜欢造轮子，搞各种怪怪的应用升级缓存模式，可能会因为scoop目录结构方式的不同而出现升级难题

**Comment by theSprog** [comment]
明白了，多谢指教
