### ISSUE TITLE
Android SDK 相关安装脚本丢失

### ISSUE THREAD

**Issue by QiE2035** [lzwme/scoop-proxy-cn#5]
这个库 [https://github.com/xfqwdsj/BucketDev/](https://github.com/xfqwdsj/BucketDev/) 的作者将 `Android SDK` 的两个安装脚本 `link.ps1`, `setup.ps1` 放置在了 `bucket` 根目录，`spc` 没能合并进来，可能需要修复一下

**Comment by renxia** [comment]
感谢反馈！
