### ISSUE TITLE
添加 bucket 链接到 sync-buckets-from 章节

### ISSUE THREAD

**Issue by amorphobia** [lzwme/scoop-proxy-cn#6]
你好，我发现这个仓库同步了[我的 bucket](https://github.com/amorphobia/siku)，希望可以把我的 bucket 链接添加到 [sync-buckets-from](https://github.com/lzwme/scoop-proxy-cn#sync-buckets-from) 章节，感谢！

**Comment by renxia** [comment]
应该是间接同步到的，我会将您的仓库加入到直接列表中。感谢！
