### ISSUE TITLE
miniconda安装报错

### ISSUE THREAD

**Issue by YUANCHUYC** [lzwme/scoop-proxy-cn#66]
![Snipaste_2024-09-27_15-20-18](https://github.com/user-attachments/assets/d68484cb-be80-4181-965e-8124b5df0987)
如果我没记错的话，好像我之前在dorado仓库安装过miniconda， 然后把那个库删掉了，准备用老哥你的牛x库， 安装脚本还是在搜我之前dorado库的脚本，搜不出来报错 安装失败， 请问这种情况该如何解决呢？

**Comment by renxia** [comment]
看了下 miniconda 的安装脚本，同步到本仓库后确实有些问题。
可以用 miniconda3 来代替，下载的安装包版本是一样的
