### ISSUE TITLE
请求更新downkyicore

### ISSUE THREAD

**Issue by NeonMedusa** [lzwme/scoop-proxy-cn#79]
https://github.com/yaobiao131/downkyicore
目前仓库里的downkyicore版本太老，已经不可用了

**Comment by renxia** [comment]
本仓库只做同步，没法直接更新的，更新了也会在下次同步时被覆盖。
可以从sync-sources.txt中看下来源是哪里，到源仓库提交更新请求

**Comment by NeonMedusa** [comment]
懂了，谢谢！
